import Image from "next/image";
import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Back to Home Link */}
      <Link
        className="flex items-center gap-2 text-gray-600 hover:text-primary mb-8 w-fit"
        href="/"
      >
        <Image alt="contact" width={20} height={20} src="/backArrow.svg" />
        Back to Home
      </Link>

      {/* Terms of Service Content */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8">
        <h1 className="text-3xl font-bold text-primary mb-6">
          Terms of Service
        </h1>
        <div className="prose max-w-none text-gray-700 space-y-6">
          <p className="text-sm text-gray-500">
            Last updated: Thursday, January 16, 2025
          </p>

          {/* Terms Sections */}
          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing and using this website, you accept and agree to be
              bound by these Terms of Service and our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              2. Use of the Website
            </h2>
            <p>
              You agree to use this website for lawful purposes only and in a
              manner that does not infringe upon or restrict others' use and
              enjoyment of the website.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              3. Intellectual Property
            </h2>
            <p>
              All content on this website, including text, graphics, logos, and
              images, is the property of the website owner and protected by
              copyright laws.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              4. User Content
            </h2>
            <p>
              If applicable, you retain ownership of any content you submit to
              the website. However, you grant us a non-exclusive license to use,
              modify, and display that content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              5. Third-Party Advertising
            </h2>
            <p>
              This website uses Google AdSense and other third-party advertising
              services. By using this site, you consent to the use of cookies
              and tracking technologies for advertising purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              6. Use of ChatGPT API
            </h2>
            <p>
              We use OpenAI's ChatGPT API to process user interactions and
              enhance our services. By using our ChatGPT-powered features, you
              agree to the following:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                You are responsible for all input provided to the ChatGPT API
                and for evaluating the accuracy and appropriateness of the
                output for your use case.
              </li>
              <li>
                Output generated by the ChatGPT API may not be unique, and other
                users may receive similar content.
              </li>
              <li>
                You must not use the ChatGPT API to generate content that is
                illegal, discriminatory, or violates our usage policies.
              </li>
              <li>
                Any legal information generated through the ChatGPT API should
                not be considered professional legal advice and must be reviewed
                by a qualified legal expert before use.
              </li>
              <li>
                You agree to comply with OpenAI's terms of service and usage
                policies when interacting with the ChatGPT API through our
                website.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              7. Disclaimer of Warranties
            </h2>
            <p>
              This website and its services, including the ChatGPT API, are
              provided "as is" without any warranties, express or implied.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              8. Limitation of Liability
            </h2>
            <p>
              We shall not be liable for any indirect, incidental, special, or
              consequential damages resulting from the use or inability to use
              the website or its services, including the ChatGPT API.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              9. Indemnification
            </h2>
            <p>
              You agree to indemnify and hold us harmless from any claims,
              damages, or expenses arising from your use of the website or
              violation of these Terms of Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              10. Governing Law
            </h2>
            <p>
              These Terms of Service shall be governed by and construed in
              accordance with the laws of Singapore.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              11. Termination
            </h2>
            <p>
              We reserve the right to terminate or suspend your access to our
              services, including ChatGPT API features, at our sole discretion,
              without notice, for conduct that we believe violates these Terms
              of Service or is harmful to other users, us, or third parties, or
              for any other reason.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mt-8 mb-4">
              12. Contact Information
            </h2>
            <p>
              For any questions regarding these Terms of Service, please contact
              us using the Contact Form.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
